
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/liuchongfaye/MDSpecs.git'
use_frameworks!

target 'MDHomeList_Example' do
  pod 'MDHomeList', :path => '../'
  
  pod 'MDHud'
  pod 'UserDetailCategory'
  
  # 不添加依赖
  pod 'UserDetail'
  
  #pod 'AFNetworking'
  
  target 'MDHomeList_Tests' do
    inherit! :search_paths

    
  end
end
